GitHub actions changes
MineInAbyss/geary-1.0 pull request #21
Opened 2020-04-20 05:30 UTC by Derongan

2020-04-20 06:06 UTC, Derongan commented
#17

2020-04-20 20:18 UTC, Derongan commented on .github/workflows/main.yml
> +on:
```suggestion
test:
```

2020-04-23 00:15 UTC, 0ffz commented on .github/workflows/main.yml
> +      - README.md
Is it worth ignoring `**.md`?

2020-04-23 00:15 UTC, 0ffz commented on .github/workflows/main.yml
> +      - name: Build NMS
No cache? :(

I'd like it if we could figure out a better way of doing it than [I have with Mobzy](https://github.com/MineInAbyss/Mobzy/blob/83165c99671b3ea51a882553fcae7e1aa68f0c69/.github/workflows/publish-snapshot.yml#L18). I wonder if it'd be possible to get that working right in the NMS action itself. The only actual problem with the way I did it is it relies on NMS version being in gradle.properties and will update cache any time properties are updated.

2020-04-23 00:15 UTC, 0ffz commented on build.gradle
> +    def plugin_path = project.findProperty("plugin_path")
What does this do if there's no plugin_path defined?

2020-04-23 01:06 UTC, Derongan commented on .github/workflows/main.yml
> +      - README.md
id prefer not to for now just in case. if it starts being annoying can change

2020-04-23 01:07 UTC, Derongan commented on .github/workflows/main.yml
> +      - name: Build NMS
seeing as this change is focused on releasing, no

2020-04-23 01:07 UTC, Derongan commented on build.gradle
> +    def plugin_path = project.findProperty("plugin_path")
throws an error as it should

2020-04-23 04:15 UTC, lizelive requested changes

2020-04-23 04:15 UTC, lizelive commented on .github/workflows/publish.yml
> +      - uses: zwaldowski/semver-release-action@v1
is this updateing the gradle version?

2020-04-23 04:15 UTC, lizelive commented on build.gradle
> +}
why change this

2020-04-23 04:15 UTC, lizelive commented on build.gradle
> +defaultTasks 'build'
why add this to our contract

2020-04-23 04:15 UTC, lizelive commented on build.gradle
> +defaultTasks 'build'
also this is not the one most users expect.

2020-04-23 04:15 UTC, lizelive commented on .github/workflows/publish.yml
> +        uses: derongan/nmsaction@v1
it may be benifcital for us to setup a private repo with nms in the future.

2020-04-23 04:15 UTC, lizelive commented on .github/workflows/publish.yml
> +        run: ./gradlew test
should this before the zwalowsi steps

2020-04-23 04:15 UTC, lizelive commented on .github/workflows/publish.yml
> +            build/libs/*.jar
not just the shadow jar?

2020-04-23 05:28 UTC, Derongan commented on build.gradle
> +defaultTasks 'build'
This probably should be left out, I agree

2020-04-23 05:28 UTC, Derongan commented on build.gradle
> +}
I decided to combine two things in this PR, because I think they should go hand in hand and this review is rather small.

1. Add a release with a version
2. Change the gradle configuration to be correct.

The previous way it was set was not correct, and I don't think it actually _did_ anything. We were setting a top level variable, but we needed to be setting it within the context of the java plugin. Additionally, the variable takes an enum of type Java version, NOT a string.

2020-04-23 05:29 UTC, Derongan commented on .github/workflows/publish.yml
> +        uses: derongan/nmsaction@v1
Agreed

2020-04-23 05:30 UTC, Derongan commented on .github/workflows/publish.yml
> +            build/libs/*.jar
Yes. My thinking was there is no harm in releasing both. The non shaded jar may be useful for explicitly adding a dependency when developing outside of gradle.

2020-04-23 05:31 UTC, Derongan commented on .github/workflows/publish.yml
> +        run: ./gradlew test
Yes, good catch.

2020-04-23 05:42 UTC, Derongan commented on .github/workflows/publish.yml
> +      - uses: zwaldowski/semver-release-action@v1
There are three main new taken.

bump: Gets the label applied to the PR, if available. If not fails. The label name is stored in `steps.bump.outputs.match`.

next_version: Looks at the git tags and finds the latest version (following semver). Depending on the value of bump, updates either the major, minor, or patch. Adds the resulting version (prefixed with the prefix) as a tag to the current ref.

Create GitHub Release: Creates a release for the current ref (which now has a semver tag yay). Git commits added since last release are added as release details.

2020-04-23 17:38 UTC, 0ffz commented on .github/workflows/publish.yml
> +        uses: derongan/nmsaction@v1
Would that be within Minecraft TOS even if it's private?

2020-04-23 17:41 UTC, 0ffz commented on .github/workflows/main.yml
> +      - name: Build NMS
Sounds good, but I'd like to look into that later. An issue would be nice, but what repo would that belong to? I think best to put it under the nms action itself, since we should probably add some  info the the README on caching anyways.

2020-04-23 17:46 UTC, 0ffz commented on build.gradle
> +    def plugin_path = project.findProperty("plugin_path")
I think it's possible someone might prefer it to not copy at all, so don't know if we should be enforcing a path. If we are, it's probably best to mention that in the README.

2020-04-23 20:09 UTC, Derongan commented on build.gradle
> +    def plugin_path = project.findProperty("plugin_path")
Build no longer depends on copyJar. You run copy jar separately.

2020-04-23 20:10 UTC, Derongan commented on .github/workflows/publish.yml
> +        uses: derongan/nmsaction@v1
Who's gonna tell? Also I'm pretty sure it's legal as long as you don't distribute.

2020-04-30 03:42 UTC, 0ffz approved these changes

2020-04-30 04:56 UTC, lizelive commented on .github/workflows/publish.yml
> +        uses: derongan/nmsaction@v1
https://github.com/microsoft/malmo is a thing. wtf is legal anyhow.

2020-04-30 04:56 UTC, lizelive approved these changes

2020-04-30 05:11 UTC, merged