Fix style in build.gradle
MineInAbyss/geary-1.0 pull request #28
Opened 2020-05-01 14:04 UTC by Paul1365972

Fixes style issues and the legacy plugin declaration

2020-05-01 19:25 UTC, Derongan requested changes
I think this whole review is more or less a nit, but not against beautification. A few changes are changing intentional behavior though.

2020-05-01 19:25 UTC, Derongan commented on build.gradle
> -buildscript {
This is a work around for issues with how gradles plugins apply in multiproject projects. If you do not do this shadow in the parent has a fight with shadow in the submodule and everything explodes.

2020-05-01 19:25 UTC, Derongan commented on build.gradle
> +    mavenCentral()
I'm not sure why moving things to be non alphabetical is a fix thats needed :P

2020-05-01 19:25 UTC, Derongan commented on build.gradle
> +            artifact tasks.shadowJar
We don't want to do this. If you have a dependency on geary you should not be automatically getting all of the transient dependencies as well... you just need geary's API.

2020-05-01 20:20 UTC, Paul1365972 commented on build.gradle
> +    mavenCentral()
I prefer logical order over alphanumerical order, mavenLocal() first so all remote repositories are grouped together :p

2020-05-01 22:27 UTC, Paul1365972 commented on build.gradle
> -buildscript {
Figured out why this happend. When including this project as a subproject the two versions of the shadow clashed (even though they are the same... anyways). The fix not being hacky with includes, but using the designated feature: [Composite Builds](https://docs.gradle.org/current/userguide/composite_builds.html)
Talked with @0ffz and will also fix this in all other plugins

2020-05-01 22:28 UTC, Paul1365972 commented on build.gradle
> +            artifact tasks.shadowJar
Fixed

2020-05-06 20:58 UTC, Derongan approved these changes

2020-05-06 20:59 UTC, Derongan approved these changes

2020-05-06 21:00 UTC, merged